### ISSUE TITLE
Startup not possible anymore - DB_PAGE_NOTFOUND

### ISSUE THREAD

**Issue by Tscherno** [piejanssens/premiumizer#110]
Have the following issue, premiumizer doesn't start anymore (don't know what changed or what happened before excactly):

05-16 12:28:53: INFO : Running at C:\Premiumizer\Premiumizer
05-16 12:28:54: ERROR : Uncaught exception
Traceback (most recent call last):
  File "C:\Premiumizer\Premiumizer\Premiumizer.py", line 500, in <module>
    if not db.keys():
  File "C:\Premiumizer\Python\lib\shelve.py", line 101, in keys
    return self.dict.keys()
  File "C:\Premiumizer\Python\lib\bsddb\__init__.py", line 303, in keys
    return _DeadlockWrap(self.db.keys)
  File "C:\Premiumizer\Python\lib\bsddb\dbutils.py", line 68, in DeadlockWrap
    return function(*_args, **_kwargs)
DBPageNotFoundError: (-30986, 'DB_PAGE_NOTFOUND: Requested page not found')

**Comment by neox387** [comment]
Delete the .db file and try to start again?
