### ISSUE TITLE
premiumizer closing with error message segmentation fault 11

### ISSUE THREAD

**Issue by ip-stivi** [piejanssens/premiumizer#133]
Hi there,
It started a few days ago that premiumizer shuts down because either it reports a "Segmentation fault 11" : 

10-21 14:55:23: INFO : Added: The Office Season 9 720p BluRay x265 HEVC- FrogPerson -- Category:  -- Type: 
Segmentation fault: 11
(virtualenv) macmini-server:premiumizer admin$ ./premiumizer.py 

or I am now getting the below error:

10-21 14:59:08: INFO : Running at /Users/admin/premiumizer
10-21 14:59:09: INFO : Watchdir is enabled at: /plex1/torrents/
10-21 14:59:09: INFO : Starting server on 192.168.1.2:5000 
10-21 14:59:09: ERROR : Uncaught exception
Traceback (most recent call last):
  File "./premiumizer.py", line 2177, in <module>
    load_tasks()
  File "./premiumizer.py", line 1672, in load_tasks
    task = db[id.encode("utf-8")]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 121, in __getitem__
    f = StringIO(self.dict[key])
KeyError: 'wnGEkdBPFVIBothDNrfYMA'

I already restarted the mac mini multiple times, shall I try to reinstall premiumizer from scratch? Thank you,

**Comment by ip-stivi** [comment]
ok I tried stopping and starting again but am getting the same Key error message now.

low or faulty ram would be a pain, I will look into this - thank you for the insight, much appreciated.
