### ISSUE TITLE
Synology Docker - Error when trying to access History

### ISSUE THREAD

**Issue by ujellyx** [piejanssens/premiumizer#145]
Clicking on the History tab produces the following error:

"Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

Log shows:
> 02-02 12:07:36: ERROR : Exception on /history [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/flask_login/utils.py", line 258, in decorated_view
    return func(*args, **kwargs)
  File "premiumizer.py", line 1848, in history
    return render_template("history.html", history=history)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/premiumizer/templates/history.html", line 2, in top-level template code
    {% set active_page = "history" %}
  File "/premiumizer/templates/base.html", line 60, in top-level template code
    {% block content %}
  File "/premiumizer/templates/history.html", line 22, in block "content"
    <TD class="c2 vert-align">{{ item.name }}</TD>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 0: ordinal not in range(128)

**Comment by neox387** [comment]
Seems to be some unicode issue not sure if related to python on Synology, clear log files and try again

**Comment by ujellyx** [comment]
Clearing the log resolved this issue. Thanks!
