### ISSUE TITLE
Crash when saving settings

### ISSUE THREAD

**Issue by gelsas** [piejanssens/premiumizer#160]
Hello,

premiumizer got updated and now I am getting an error when I try to save my settings:

[2019-03-11 15:29:24,032] ERROR in app: Exception on /settings [POST]
Traceback (most recent call last):
  File "C:\Users\gelsas\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\gelsas\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\gelsas\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\gelsas\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\gelsas\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\gelsas\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\gelsas\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask_login\utils.py", line 258, in decorated_view
    return func(*args, **kwargs)
  File "premiumizer.py", line 2068, in settings
    prem_config.set('downloads', 'jd_username', request.form.get('jd_username'))
  File "C:\Users\gelsas\AppData\Local\Programs\Python\Python37-32\lib\configparser.py", line 1197, in set
    self._validate_value_types(option=option, value=value)
  File "C:\Users\gelsas\AppData\Local\Programs\Python\Python37-32\lib\configparser.py", line 1182, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings

**Comment by neox387** [comment]
This didnt happen before The update?

You have something weird in the field:
JD Username?

**Comment by gelsas** [comment]
No this happened after the update.

In my JD Username field is my email address. It worked perfectly fine before the update.

**Comment by neox387** [comment]
@piejanssens slap ^^

**Comment by piejanssens** [comment]
@gelsas Please test again.

**Comment by gelsas** [comment]
Works perfect, thanks!
