### ISSUE TITLE
No luck on qnap

### ISSUE THREAD

**Issue by theincogtion** [piejanssens/premiumizer#192]
I have a qnap arm device and would like to use premiumizer.
I was not able to compile it due to python problems
I would be happy if I could help to get your tool on qnap.
`[~] # git clone https://github.com/piejanssens/premiumizer.git premiumizer
Cloning into 'premiumizer'...
remote: Enumerating objects: 91, done.
remote: Counting objects: 100% (91/91), done.
remote: Compressing objects: 100% (57/57), done.
remote: Total 4233 (delta 44), reused 69 (delta 30), pack-reused 4142
Receiving objects: 100% (4233/4233), 4.70 MiB | 4.92 MiB/s, done.
Resolving deltas: 100% (2343/2343), done.
`

`[~] # cd premiumizer
[~/premiumizer] # pip install virtualenv
Traceback (most recent call last):
  File "/opt/bin/pip", line 7, in <module>
    from pip import main
ImportError: cannot import name main
[~/premiumizer] # pip
pip     pip2    pip2.7  pip3    pip3.7
[~/premiumizer] # pip
pip     pip2    pip2.7  pip3    pip3.7
[~/premiumizer] # pip3.7 install virtualenv
Collecting virtualenv
  Downloading https://files.pythonhosted.org/packages/c4/9a/a3f62ac5122a65dec34a                                                   d4b5ed8d802633dae4bc06a0fc62e55fe3e96fe1/virtualenv-16.6.1-py2.py3-none-any.whl                                                    (2.0MB)
    100% |████████████████████████████████| 2.0MB 5.1MB/s
Installing collected packages: virtualenv
Successfully installed virtualenv-16.6.1
You are using pip version 18.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[~/premiumizer] # pip install --upgrade pip
Traceback (most recent call last):
  File "/opt/bin/pip", line 7, in <module>
    from pip import main
ImportError: cannot import name main
[~/premiumizer] # pip3.7 install --upgrade pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/5c/e0/be401c003291b56efc55                                                   aeba6a80ab790d3d4cece2778288d65323009420/pip-19.1.1-py2.py3-none-any.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 4.9MB/s
Installing collected packages: pip
  Found existing installation: pip 18.1
    Uninstalling pip-18.1:
      Successfully uninstalled pip-18.1
Successfully installed pip-19.1.1
`
So far it worked.
Problem begins here:
` virtualenv -p /usr/local/bin/python3 env`
/usr/local/bin/python3 does not exist on my system
only

- python
- python2    
- python2.7

I reinstalled python3 with opkg but no luck.
i found 
python3 in 
/opt/bin/python3

`virtualenv -p /opt/bin/python3 env
Already using interpreter /opt/bin/python3
Using base prefix '/opt'
New python executable in /env/bin/python3
Also creating executable in /env/bin/python
Fatal Python error: initfsencoding: Unable to get the locale encoding
Traceback (most recent call last):
  File "/__init__.py", line 33, in <module>
ImportError: cannot import name 'aliases' from 'encodings' (/env/lib/python3.7/encodings/__init__.pyc)
ERROR: The executable /env/bin/python3 is not functioning
ERROR: It thinks sys.prefix is '/' (should be '/env')
ERROR: virtualenv is not compatible with this system or executable
`

**Comment by theincogtion** [comment]
Forget it :)
Here is the solution:
https://www.qnapclub.eu/en/qpkg/696
