### ISSUE TITLE
Exception when opening history page

### ISSUE THREAD

**Issue by cremor** [piejanssens/premiumizer#202]
I just updated to the latest Docker image (with commit f64641189ade86f08d1a0d57f745af36e6c8d625). I now get an exception when I try to open the history page:

```
07-05 17:24:08: ERROR : Exception on /history [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_login/utils.py", line 258, in decorated_view
    return func(*args, **kwargs)
  File "./premiumizer/premiumizer.py", line 2033, in history
    return render_template("history.html", history=history)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/premiumizer/premiumizer/templates/history.html", line 2, in top-level template code
    {% set active_page = "history" %}
  File "/premiumizer/premiumizer/templates/base.html", line 66, in top-level template code
    {% block content %}
  File "/premiumizer/premiumizer/templates/history.html", line 56, in block "content"
    {% for line in item.info.splitlines() %}
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'info'
```

**Comment by neox387** [comment]
Delete your log files and restart , should work afterwards, guess it did not get deleted by itself with some tars Docker permission donno xP

**Comment by cremor** [comment]
Works again, thanks.

Although it is a bit weird that clearing the log also clears the history. I would have assumed those are two separate things.

**Comment by neox387** [comment]
It's just easyer haha
