### ISSUE TITLE
[Request] File extension blacklist

### ISSUE THREAD

**Issue by cremor** [piejanssens/premiumizer#223]
It is already possible to configure a file extension whitelist for each category. But I'd like to use a blacklist instead.

Since it doesn't make sense to use a whitelist and a blacklist at the same time, maybe just add a checkbox/dropdown to select whether the file extension list should be treated as a whitelist or blacklist.

**Comment by cremor** [comment]
@neox387 Seems like you implemented this, thanks! I've updated to commit 4311b97 to test it, but I have problems now.

1) During startup, the line "ERROR : Could not update settings file" is logged (without any additional information).

2) When I try to open the settings page, the following error is logged:

```
ERROR : Exception on /settings [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/configparser.py", line 788, in get
    value = d[option]
  File "/usr/local/lib/python3.7/collections/__init__.py", line 916, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/local/lib/python3.7/collections/__init__.py", line 908, in __missing__
    raise KeyError(key)
KeyError: 'cat_ext_blacklist[1]'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_login/utils.py", line 258, in decorated_view
    return func(*args, **kwargs)
  File "./premiumizer/premiumizer.py", line 2276, in settings
    return render_template('settings.html', settings=prem_config, cfg=cfg, categories_amount=categories_amount)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/premiumizer/premiumizer/templates/settings.html", line 2, in top-level template code
    {% set active_page = "settings" %}
  File "/premiumizer/premiumizer/templates/base.html", line 66, in top-level template code
    {% block content %}
  File "/premiumizer/premiumizer/templates/settings.html", line 383, in block "content"
    {% if settings.get('categories', 'cat_ext_blacklist['+x|string+']') == '1' %}
  File "/usr/local/lib/python3.7/configparser.py", line 791, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'cat_ext_blacklist[1]' in section: 'categories'
```

I've already tried clearing the log and restarting Premiumizer, but it didn't help.

**Comment by neox387** [comment]
probbably docker problem that it aint allowed to update the settings for some reason does your settings.cfg have config_version = 2.7 ?

you could mannualy add
cat_ext_blacklist[1] = 0
cat_ext_blacklist[2] = 0
cat_ext_blacklist[3] = 0
cat_ext_blacklist[4] = 0
cat_ext_blacklist[5] = 0
cat_ext_blacklist[6] = 0

to the file then it should work.

**Comment by cremor** [comment]
Oh yes, it was a permissions issue. Seems like I broke them when I last changed something in the settings file manually. After restoring the right permissions everything works fine. Sorry!

**Comment by cremor** [comment]
@neox387 It seems like there is a problem with the blacklist feature. My downloads are not starting any more, I always get this error in the log:

> ERROR : Error for abc: Nothing to download .. Filtered out or bad torrent/nzb ?

I have only one file extension in my blacklist and it there isn't any file that matches it, so everything should be downloaded.
This error happens as soon as the "blacklist ext" toggle is switched on. I don't even have to enter any file extension.

**Comment by neox387** [comment]
ye I see was still fuckt should finally be working after next pr :/ sorry

**Comment by cremor** [comment]
Works fine now, thanks!
