### ISSUE TITLE
Windows - downloads not being sent to jdownloader

### ISSUE THREAD

**Issue by bkcberry** [piejanssens/premiumizer#231]
The files are in my premiumize.me account, but on the premiumizer homepage they just say Failed: download retrying soon. The error below shows up in the debug log

```
10-04 11:55:57       apscheduler.executors.downloads          : ERROR    : Job "Back to the Future III (1990) (trigger: date[2019-10-04 11:55:53 CDT], next run at: 2019-10-04 11:55:53 CDT)" raised an exception
Traceback (most recent call last):
  File "C:\Premiumizer\Python\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Premiumizer\Premiumizer\premiumizer\Premiumizer.py", line 1440, in download_task
    failed = download_process()
  File "C:\Premiumizer\Premiumizer\premiumizer\Premiumizer.py", line 1427, in download_process
    returncode = download_file()
  File "C:\Premiumizer\Premiumizer\premiumizer\Premiumizer.py", line 1283, in download_file
    if len(query_links):
TypeError: object of type 'bool' has no len()
```

**Comment by bkcberry** [comment]
I tentatively think this was because i had a different number of max simultaneous downloads set in jdownloader vs premiumizer

**Comment by neox387** [comment]
Mm if query_links is a boolean it probably means there are no downloads running In Jdownloader.

Connection to my jdownloader is working probably because Download starts, is there nothing in Jdownloader? Or restart jdownloader and premiumizer?
