### ISSUE TITLE
Docker failure

### ISSUE THREAD

**Issue by nihilist77** [piejanssens/premiumizer#312]
Suddenly docker container is failing with 'Could not update requirements'. For this, any new torrent is not recognized in the watch directory. Apparently this happens [here](https://github.com/piejanssens/premiumizer/blob/b7b5f367d0f77c5b8e542b96a0f7f737327469ec/premiumizer/premiumizer.py#L286).

Digging into this, the `update.req_version` in `prem_config` is `10.1`. But the same for `default_config` is `10.2`. So it's getting into that loop and failing.

Log from docker,

```
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in /usr/local/lib/python3.7/site-packages (21.1.2)
Collecting pip
  Downloading pip-21.1.3-py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  WARNING: The scripts pip, pip3 and pip3.7 are installed in '/home/premiumizer/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-21.1.3
WARNING: You are using pip version 21.1.2; however, version 21.1.3 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/requirements.txt'
07-02 23:14:06: ERROR : Could not update requirements
ERROR:Rotating log:Could not update requirements
07-02 23:14:06: INFO : Watchdir is enabled at: /blackhole
INFO:Rotating log:Watchdir is enabled at: /blackhole
07-02 23:14:06: INFO : Starting server on 0.0.0.0:5000
INFO:Rotating log:Starting server on 0.0.0.0:5000
```

**Comment by nihilist77** [comment]
It turned out to be a inotify issue.

```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/app/premiumizer.py", line 2045, in watchdir
    observer.start()
  File "/usr/local/lib/python3.7/site-packages/watchdog/observers/api.py", line 256, in start
    emitter.start()
  File "/usr/local/lib/python3.7/site-packages/watchdog/utils/__init__.py", line 93, in start
    self.on_thread_start()
  File "/usr/local/lib/python3.7/site-packages/watchdog/observers/inotify.py", line 118, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/usr/local/lib/python3.7/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
    self._inotify = Inotify(path, recursive)
  File "/usr/local/lib/python3.7/site-packages/watchdog/observers/inotify_c.py", line 199, in __init__
    self._add_dir_watch(path, recursive, event_mask)
  File "/usr/local/lib/python3.7/site-packages/watchdog/observers/inotify_c.py", line 396, in _add_dir_watch
    self._add_watch(path, mask)
  File "/usr/local/lib/python3.7/site-packages/watchdog/observers/inotify_c.py", line 417, in _add_watch
    Inotify._raise_error()
  File "/usr/local/lib/python3.7/site-packages/watchdog/observers/inotify_c.py", line 429, in _raise_error
    raise OSError(errno.ENOSPC, "inotify watch limit reached")
OSError: [Errno 28] inotify watch limit reached
2021-07-07T20:32:04Z <Greenlet at 0x7fe78b239950: watchdir> failed with OSError
```
I had to increase `fs.inotify.max_user_watches` and everything is fine now.
