### ISSUE TITLE
Docker crashes after enabling blackhole.

### ISSUE THREAD

**Issue by jaddel** [piejanssens/premiumizer#321]
```
10-20 08:58:57: INFO : Starting server on 0.0.0.0:5000
10-20 08:59:54: INFO : Settings saved, reloading configuration
10-20 08:59:54: INFO : Watchdir is enabled at:
[2021-10-20 08:59:54,244] ERROR in app: Exception on /settings [POST]

Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.7/site-packages/flask_login/utils.py", line 269, in decorated_view
return func(*args, **kwargs)
File "/app/premiumizer.py", line 2345, in settings
cfg.check_config()
File "/app/premiumizer.py", line 419, in check_config
os.makedirs(self.watchdir_location)
File "/usr/local/lib/python3.7/os.py", line 223, in makedirs
mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Comment by neox387** [comment]
watchdir_location is empty? small bug then

**Comment by jaddel** [comment]
This folders are shared via docker.
![image](https://user-images.githubusercontent.com/46263124/138051467-253ca25c-5f18-476c-860f-220902b085ca.png)

So the  config has to look like this right?

[upload]
watchdir_enabled = 1
watchdir_location = /blackhole 
watchdir_walk_enabled = 0
watchdir_walk_interval = 60

**Comment by neox387** [comment]
Yes should be good inside the blackhole folder it makes same folders like the categories.

Download location in categories is of you want to change it to something else, IF you say add categorie games it will make a new folders games in the download location folder and blackhole
