### ISSUE TITLE
Bug with freeNas (freeBSD) and apscheduler

### ISSUE THREAD

**Issue by xerg0n** [piejanssens/premiumizer#33]
When running Premiumizer on freeNas 9.10 it crashes with the following stack trace:
```
Traceback (most recent call last):                                                                                                  
  File "./Premiumizer.py", line 1411, in <module>                                                                                   
    seconds=active_interval, replace_existing=True, max_instances=1, coalesce=True)                                                 
  File "/virtualenv/lib/python2.7/site-packages/apscheduler/schedulers/base.py", line 366, in add_job                               
    'trigger': self._create_trigger(trigger, trigger_args),                                                                         
  File "/virtualenv/lib/python2.7/site-packages/apscheduler/schedulers/base.py", line 848, in _create_trigger                       
    return self._create_plugin_instance('trigger', trigger, trigger_args)                                                           
  File "/virtualenv/lib/python2.7/site-packages/apscheduler/schedulers/base.py", line 833, in _create_plugin_instance               
    return plugin_cls(**constructor_kwargs)                                                                                         
  File "/virtualenv/lib/python2.7/site-packages/apscheduler/triggers/interval.py", line 37, in __init__                             
    self.timezone = astimezone(timezone)                                                                                            
  File "/virtualenv/lib/python2.7/site-packages/apscheduler/util.py", line 77, in astimezone                                        
    'Unable to determine the name of the local timezone -- you must explicitly '                                                    
ValueError: Unable to determine the name of the local timezone -- you must explicitly specify the name of the local timezone. Please
 refrain from using timezones like EST to prevent problems with daylight saving time. Instead, use a locale based timezone name (suc
h as Europe/Helsinki).`
```

This looks like an apscheduler bug but i am not sure. 

Update:
Ok i found the reason, its a problem with tzlocal. Its unable to read the correct time zone on freeBSD systems. 
There is a pull request [here](https://github.com/regebro/tzlocal/pull/34) but it has not been accepted yet.

**Comment by xerg0n** [comment]
I tested the pull request mentiond above and everything works great on freeBSD now

**Comment by matrixpolic** [comment]
i also met this problem;
solve:
sched = BlockingScheduler(timezone="UTC")

**Comment by Darktex** [comment]
You can also set up the timezone without changing the code.

I did two things, not sure which one worked but both are quick.

1) Set up your timezone as a system var:
`export TZ=America/Los_Angeles`
2) Change the zonefile as described here: https://www.cyberciti.biz/faq/howto-set-date-and-time-timezone-in-freebsd/

**Comment by xerg0n** [comment]
For freebsd its not `export`, but rater `setenv`. 
This error can be fixed by running e.g. `setenv TZ Europe/Berlin`
