### ISSUE TITLE
Can't download files that are located in "my files"

### ISSUE THREAD

**Issue by hurfi** [piejanssens/premiumizer#354]
Premiumizer can see the files remaining in the transfers list in premiumizer.me but isn't showing anything that has completed and has been moved to "my files"

If I copy and paste a download link into "filehost links" to the file located in my files and assign a category, it adds it to the queue, but the progress stays at 0% and it isn't sent to aria2

If I assign a category to any of the files remaining in the transfers list that premiumizer grabs from premiumizer.me it sends to job to aria2 and starts the download.

All my downloads on premiumizer.me have finished and are now in the "my files" section

Essentially, is there a way to specify the folder ID from premiumize.me that premiumizer looks in for files?

**Comment by hurfi** [comment]
Here's the debug log...I've removed the filename and replaced with **file name removed**

11-08 00:42:29       root                                     : INFO     : Downloading: **file name removed**-- id: d74575a13e9145748a5d456c245cf5af
11-08 00:42:29       root                                     : DEBUG    : def download_file started
11-08 00:42:29       root                                     : DEBUG    : def prem_connection started
11-08 00:42:29       urllib3.connectionpool                   : DEBUG    : https://www.premiumize.me:443 "POST /api/transfer/directdl HTTP/1.1" 200 None
11-08 00:42:29       apscheduler.executors.downloads          : ERROR    : Job "**file name removed**" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/premiumizer.py", line 1596, in download_task
    failed = download_process()
  File "/app/premiumizer.py", line 1583, in download_process
    returncode = download_file()
  File "/app/premiumizer.py", line 1372, in download_file
    download['combined_path'] = os.path.join(greenlet.task.dldir, download['combined_path'])
KeyError: 'combined_path'
11-08 00:42:45       geventwebsocket.handler                  : DEBUG    : Initializing WebSocket
11-08 00:42:45       geventwebsocket.handler
