### ISSUE TITLE
Docker container not working

### ISSUE THREAD

**Issue by sflix** [piejanssens/premiumizer#359]
Hello, docker container crashes on start at least from tag 2fe980f5.
V. d9c2e342 is working with at least the following error:  uploads nzb from blackhole folder, but it does not download.

attaching log:

date	stream	content
2023-02-05T04:06:06.236314940Z	stdout	tzlocal.utils.ZoneInfoNotFoundError: 'tzlocal() does not support non-zoneinfo timezones like %s. \nPlease use a timezone in the form of Continent/City'
2023-02-05T04:06:06.236250356Z	stdout	    raise ZoneInfoNotFoundError(
2023-02-05T04:06:06.236071397Z	stdout	  File "/usr/local/lib/python3.10/site-packages/tzlocal/utils.py", line 125, in _tz_from_env
2023-02-05T04:06:06.235984573Z	stdout	    tzenv = utils._tz_from_env()
2023-02-05T04:06:06.235913062Z	stdout	  File "/usr/local/lib/python3.10/site-packages/tzlocal/unix.py", line 161, in _get_localzone
2023-02-05T04:06:06.235856135Z	stdout	    _cache_tz = _get_localzone()
2023-02-05T04:06:06.235760614Z	stdout	  File "/usr/local/lib/python3.10/site-packages/tzlocal/unix.py", line 203, in get_localzone
2023-02-05T04:06:06.235666446Z	stdout	    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
2023-02-05T04:06:06.235589571Z	stdout	  File "/usr/local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 701, in _configure
2023-02-05T04:06:06.235524623Z	stdout	    self._configure(config)
2023-02-05T04:06:06.235451080Z	stdout	  File "/usr/local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 131, in configure
2023-02-05T04:06:06.235377486Z	stdout	    self.configure(gconfig, **options)
2023-02-05T04:06:06.235295298Z	stdout	  File "/usr/local/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 87, in __init__
2023-02-05T04:06:06.235240715Z	stdout	    scheduler = APScheduler(GeventScheduler())
2023-02-05T04:06:06.235170141Z	stdout	  File "/app/premiumizer.py", line 2758, in <module>
2023-02-05T04:06:06.235087224Z	stdout	Traceback (most recent call last):
2023-02-05T04:06:06.234935088Z	stdout	02-05 04:06:06: ERROR : Uncaught exception
2023-02-05T04:06:06.228600414Z	stdout	02-05 04:06:06: INFO : Starting server on 0.0.0.0:5000 
2023-02-05T04:06:06.160405885Z	stdout	02-05 04:06:06: INFO : *************************************************************************************
2023-02-05T04:06:06.160328957Z	stdout	02-05 04:06:06: INFO : ---------------------------Premiumizer has been updated!!----------------------------
2023-02-05T04:06:06.160232082Z	stdout	02-05 04:06:06: INFO : *************************************************************************************
2023-02-05T04:06:06.160149790Z	stdout	02-05 04:06:06: INFO : *************************************************************************************
2023-02-05T04:06:06.160079529Z	stdout	02-05 04:06:06: INFO : ----------------Premiumizer.log file has been deleted as a precaution----------------
2023-02-05T04:06:06.159914997Z	stdout	02-05 04:06:06: INFO : *************************************************************************************
2023-02-05T04:06:06.154149962Z	stdout	Logs at  /conf/logs
2023-02-05T04:06:06.154077149Z	stdout	Conf at  /conf
2023-02-05T04:06:06.154022461Z	stdout	Root at  /
2023-02-05T04:06:06.153936991Z	stdout	Runtime at  /app
2023-02-05T04:06:06.153711053Z	stdout	------------------------------------------------------------------------------------------------------------
2023-02-05T04:06:06.153640792Z	stdout	|                                                                                                           |
2023-02-05T04:06:06.153567510Z	stdout	-------------------------------------------WELCOME TO PREMIUMIZER-------------------------------------------
2023-02-05T04:06:06.153485530Z	stdout	|                                                                                                           |
2023-02-05T04:06:06.152816047Z	stdout	------------------------------------------------------------------------------------------------------------

**Comment by DatPat** [comment]
I got the same problem

**Comment by piejanssens** [comment]
This might be because of a missing docker environment variable named 'TZ' containing your time zone.

**Comment by sflix** [comment]
I did put TZ variable.
